language: node_js

node_js:
  - 'node'
  - '10'
  - '8'

branches:
  only:
  - master

install:
  - yarn

script:
  - yarn install
  - yarn test

deploy:
  - provider: npm
    email: meomeocf98@gmail.com
    api_token: $TOKEN_GITHUB
    registry: https://npm.pkg.github.com
    edge:
      branch: master


cache:
  directories:
    - node_modules

